// js/header.js
(() => {
  const ROUTES = {
    de: { home:"/de/", about:"/de/ueber-uns/", contact:"/de/kontakt/", projects:"/de/projekte/", services:"/de/konfigurator/", process:"/de/prozess/", blog:"/de/blog/" },
    en: { home:"/en/", about:"/en/about/", contact:"/en/contact/", projects:"/en/projects/", services:"/en/configurator/", process:"/en/process/", blog:"/en/blog/" },
    tr: { home:"/tr/", about:"/tr/hakkimizda/", contact:"/tr/iletisim/", projects:"/tr/projeler/", services:"/tr/configurator/", process:"/tr/surec/", blog:"/tr/blog/" },
    fr: { home:"/fr/", about:"/fr/a-propos/", contact:"/fr/contact/", projects:"/fr/projets/", services:"/fr/configurator/", process:"/fr/processus/", blog:"/fr/blog/" },
  };

  const LABELS = {
    de: { home:"Startseite", about:"Über uns (coming soon)", contact:"Kontakt", projects:"Projekte(coming soon)", services:"Konfigurator", process:"Prozess(coming soon)", blog:"Blog(coming soon)", search:"Suche", theme:"Dim", search_ph:"Suchbegriff eingeben", menu:"Menü" },
    en: { home:"Home",      about:"About (coming soon)",     contact:"Contact", projects:"Projects(coming soon)", services:"Configurator", process:"Process(coming soon)", blog:"Blog(coming soon)", search:"Search", theme:"Dim", search_ph:"Search…", menu:"Menu" },
    tr: { home:"Ana Sayfa", about:"Hakkımızda (coming soon)", contact:"İletişim", projects:"Projeler(coming soon)", services:"Configurator", process:"Süreç(coming soon)", blog:"Blog(coming soon)", search:"Ara", theme:"Dim", search_ph:"Ara…", menu:"Menü" },
    fr: { home:"Accueil",   about:"À propos (coming soon)",   contact:"Contact", projects:"Projets(coming soon)", services:"Configurator", process:"Processus(coming soon)", blog:"Blog(coming soon)", search:"Recherche", theme:"Dim", search_ph:"Rechercher…", menu:"Menu" },
  };

  const LOGO_SRC = "/assets/images/dva-logo.png";
  const PAGEFIND_MODULE_PATH = "/_pagefind/pagefind.js";

  /* =========================================================
     ✅ Social Bar config (same UI everywhere, generated by header)
     ========================================================= */
  const SOCIAL = {
    x:        { href: "https://x.com/",              label: "X",        icon: "/assets/icons/x.png" },
    instagram:{ href: "https://www.instagram.com/",  label: "Instagram",icon: "/assets/icons/instagram.png" },
    youtube:  { href: "https://www.youtube.com/",    label: "YouTube",  icon: "/assets/icons/youtube.png" },
    linkedin: { href: "https://www.linkedin.com/",   label: "LinkedIn", icon: "/assets/icons/linkedin.png" },
  };

  const SOCIAL_STATE_KEY = "dvFloatSocialCollapsed";

  // Inject header.css directly from JS (so you can delete /assets/css/header.css)
  function injectHeaderCSS() {
    if (document.getElementById("dvayd-header-css")) return;

    const style = document.createElement("style");
    style.id = "dvayd-header-css";

    style.textContent = `
/* =========================
   HEADER CSS (Injected)
   ========================= */

/* Root vars (global ok) */
:root{ --hdr-h:72px; --max:1180px; }

/* =========================================================
   SCOPE: only inside #site-header mount (prevents collisions)
   ========================================================= */
#site-header .hdr{
  position:fixed;
  inset:0 0 auto 0;
  height:var(--hdr-h);
  z-index:100;
  background:transparent;
  pointer-events:none;
  transform: translateY(0);
  transition: transform .28s cubic-bezier(.2,.9,.2,1), background .18s ease, backdrop-filter .18s ease;
  will-change: transform;
}
#site-header .hdr.is-hidden{ transform: translateY(calc(-1 * var(--hdr-h))); }
#site-header .hdr.is-scrolled{
  background: rgba(0,0,0,.10);
  backdrop-filter: blur(10px) saturate(1.2);
  -webkit-backdrop-filter: blur(10px) saturate(1.2);
}

#site-header .hdr-inner{
  pointer-events:auto;
  height:100%;
  width:min(var(--max), calc(100% - 40px));
  margin:0 auto;
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:16px;
  min-width:0;
}

/* =========================
   BRAND
   ========================= */
#site-header .brand{
  display:flex; align-items:center; gap:12px;
  color:#fff; text-decoration:none;
  font-weight:700; letter-spacing:.2px;
  min-width:200px;
  flex: 0 0 auto;
}
#site-header .brand img{
  width:36px; height:36px;
  object-fit:contain;
  display:block;
  filter: drop-shadow(0 10px 26px rgba(0,0,0,.55));
}
#site-header .brand span{
  font-size:14px;
  opacity:.95;
  text-shadow: 0 10px 26px rgba(0,0,0,.55);
}

/* =========================
   RIGHT AREA
   ========================= */
#site-header .right{
  display:flex;
  align-items:center;
  gap:12px;
  flex: 1 1 auto;
  justify-content:flex-end;
  min-width:0;
}

/* =========================
   SEARCH (Dropdown)
   ========================= */
#site-header .site-search{
  position:relative;
  display:flex;
  align-items:center;
  gap:10px;
  height:46px;
  width: min(420px, 42vw);
  padding:0 10px 0 16px;
  border-radius:18px;
  background: rgba(255,255,255,.08);
  border: 1px solid rgba(255,255,255,.14);
  backdrop-filter: blur(14px) saturate(1.4);
  -webkit-backdrop-filter: blur(14px) saturate(1.4);
  box-shadow: 0 14px 40px rgba(0,0,0,.22), inset 0 1px 0 rgba(255,255,255,.18);
  transition: background .2s ease, box-shadow .2s ease;
  z-index: 9999;
  min-width:0;
}
#site-header .site-search:hover{ background: rgba(255,255,255,.12); }

#site-header .site-search input{
  flex:1;
  min-width:0;
  height:100%;
  border:0;
  outline:0;
  background:transparent;
  color:#fff;
  font-size:14px;
  font-weight:650;
  letter-spacing:.01em;
}
#site-header .site-search input::placeholder{
  color: rgba(255,255,255,.75);
  font-weight:500;
}

#site-header .site-search .search-icon{
  width:36px;
  height:36px;
  border:0;
  background:transparent;
  padding:0;
  cursor:pointer;
  display:grid;
  place-items:center;
  flex: 0 0 auto;
}
#site-header .site-search .search-icon img{
  width:18px;
  height:18px;
  object-fit:contain;
  opacity:.9;
  filter: drop-shadow(0 6px 14px rgba(0,0,0,.35)) brightness(1.05);
  transition: opacity .15s ease, transform .15s ease;
}
#site-header .site-search .search-icon:hover img{ opacity:1; transform: scale(1.08); }

#site-header .search-dd{
  position:absolute;
  top: calc(100% + 10px);
  right:0;
  width: 100%;
  max-height: 52vh;
  overflow:auto;
  border-radius:18px;
  background: rgba(0,0,0,.55);
  border: 1px solid rgba(255,255,255,.12);
  backdrop-filter: blur(18px) saturate(1.35);
  -webkit-backdrop-filter: blur(18px) saturate(1.35);
  box-shadow: 0 30px 90px rgba(0,0,0,.45), inset 0 1px 0 rgba(255,255,255,.10);
  padding: 10px;
  display:none;
}
#site-header .search-dd.is-open{ display:block; }

#site-header .dd-row{
  display:block;
  padding: 12px 12px;
  border-radius: 14px;
  text-decoration:none;
  color: rgba(255,255,255,.92);
  transition: background .15s ease, transform .15s ease;
}
#site-header .dd-row:hover{ background: rgba(255,255,255,.07); transform: translateY(-1px); color:#fff; }
#site-header .dd-row.is-active{
  background: rgba(255,255,255,.18);
  box-shadow: 0 12px 40px rgba(0,0,0,.35), inset 0 1px 0 rgba(255,255,255,.25);
}
#site-header .dd-title{ font-weight:850; letter-spacing:.01em; margin-bottom: 4px; line-height:1.2; }
#site-header .dd-meta{ font-size:12px; opacity:.75; line-height:1.35; }
#site-header .dd-empty,
#site-header .dd-loading{ padding: 10px 12px; color: rgba(255,255,255,.80); font-weight:700; }

#site-header .search-dd mark{
  background: rgba(255,255,255,.12);
  color:#fff;
  border-radius:6px;
  padding:0 4px;
}

/* =========================
   THEME TOGGLE
   ========================= */
#site-header .theme-btn{
  width:42px; height:42px;
  display:grid; place-items:center;
  border-radius:14px;
  background: rgba(255,255,255,.06);
  border: 1px solid rgba(255,255,255,.10);
  color:#fff;
  cursor:pointer;
  box-shadow: 0 12px 30px rgba(0,0,0,.18), inset 0 1px 0 rgba(255,255,255,.12);
  filter: drop-shadow(0 10px 26px rgba(0,0,0,.25));
  transition: transform .15s ease, filter .15s ease, background .15s ease;
  flex: 0 0 auto;
}
#site-header .theme-btn:hover{
  filter: brightness(1.08) drop-shadow(0 10px 26px rgba(0,0,0,.25));
  transform: translateY(-1px);
}
#site-header .theme-btn .sun{ display:none; }
#site-header .theme-btn.is-dim .moon{ display:none; }
#site-header .theme-btn.is-dim .sun{ display:block; }
#site-header .theme-btn:not(.is-dim) .moon{ display:block; }

/* =========================
   LANGS + BURGER
   ========================= */
#site-header .langs{
  display:flex; align-items:center; gap:8px;
  color:#fff; font-weight:800; font-size:12px;
  letter-spacing:.08em; text-transform:uppercase;
  text-shadow: 0 10px 26px rgba(0,0,0,.55);
  user-select:none;
  flex: 0 0 auto;
}
#site-header .langs a{ color:#fff; opacity:.70; text-decoration:none; cursor:pointer; }
#site-header .langs a.is-active{ opacity:1; }
#site-header .langs .sep{ opacity:.35; font-weight:700; }

#site-header .burger{
  width:42px; height:42px;
  display:grid; place-items:center;
  border:0; background:transparent;
  cursor:pointer; padding:0;
  flex: 0 0 auto;
}
#site-header .burger .icon{
  width:22px; height:14px;
  display:flex; flex-direction:column;
  justify-content:space-between;
  filter: drop-shadow(0 10px 26px rgba(0,0,0,.55));
}
#site-header .burger .icon i{
  display:block; height:2px;
  border-radius:999px;
  background:rgba(255,255,255,.95);
}

/* =========================
   OVERLAY + DRAWER
   ========================= */
#site-header .overlay{
  position:fixed; inset:0;
  background: radial-gradient(900px 700px at 80% 15%, rgba(255,255,255,.08), rgba(0,0,0,.02)), rgba(0,0,0,.02);
  opacity:0;
  pointer-events:none;
  transition: opacity .10s ease;
  z-index:200;
}
#site-header .overlay.is-open{ opacity:1; pointer-events:auto; }

#site-header .drawer{
  position:fixed; top:0; right:0;
  height:100%;
  width:min(380px, 90vw);
  padding:18px 18px 22px;
  z-index:201;

  background:
    linear-gradient(135deg, rgba(255,255,255,.04), rgba(255,255,255,.015)),
    radial-gradient(900px 650px at 30% 10%, rgba(255,255,255,.008), rgba(255,255,255,0)),
    radial-gradient(900px 700px at 80% 80%, rgba(120,190,255,.04), rgba(0,0,0,0));
  border-left: 1px solid rgba(255,255,255,.10);

  box-shadow: -16px 0 60px rgba(0,0,0,.28), inset 0 1px 0 rgba(255,255,255,.14);

  backdrop-filter: blur(26px) saturate(1.55);
  -webkit-backdrop-filter: blur(26px) saturate(1.55);

  transform: translateX(112%);
  transition: transform .55s cubic-bezier(.16, 1, .12, 1);
}
#site-header .drawer.is-open{ transform: translateX(0); }

#site-header .drawer-top{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  margin-bottom:12px;
  color:#fff;
}
#site-header .drawer-top .title{ font-weight:900; letter-spacing:.02em; }

#site-header .close{
  width:42px; height:42px;
  border-radius:14px;
  border:0;
  background: rgba(255,255,255,.05);
  color:#fff;
  cursor:pointer;
  box-shadow: 0 12px 30px rgba(0,0,0,.20), inset 0 1px 0 rgba(255,255,255,.14);
}

#site-header .drawer nav{ display:flex; flex-direction:column; gap:6px; padding-top:6px; }
#site-header .drawer nav a{
  padding:14px 10px;
  border-radius:14px;
  color:rgba(255,255,255,.92);
  text-decoration:none;
  font-weight:850;
}
#site-header .drawer nav a:hover{ background: rgba(255,255,255,.07); }

/* =========================
   RESPONSIVE
   ========================= */

@media (max-width: 980px){
  #site-header .site-search{
    width: min(320px, 36vw);
    height: 44px;
  }
}

@media (max-width: 820px){
  #site-header .site-search{ display:flex; }
  #site-header .brand{ min-width: 0; }
}

/* <= 520px: Logo | Search | Theme | Burger */
@media (max-width: 520px){
  #site-header .hdr{ height:auto; }
  #site-header .hdr-inner{
    height:auto;
    width: calc(100% - 24px);
    flex-wrap: nowrap;
    gap:10px;
    padding: 10px 0;
  }

  #site-header .brand{ min-width:0; }
  #site-header .brand span{ display:none; }
  #site-header .langs{ display:none; }

  #site-header .site-search{
    flex: 1 1 auto;
    width: auto;
    min-width: 0;
    height: 38px;
    border-radius: 999px;
    padding: 0 10px 0 12px;
  }
  #site-header .site-search input{
    font-size: 13px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  #site-header .theme-btn{ width:40px; height:40px; }
  #site-header .burger{ width:40px; height:40px; }

  #site-header .search-dd{ left:0; right:0; width:100%; }
}

@media (max-width: 360px){
  #site-header .site-search{ height: 36px; }
  #site-header .site-search .search-icon{ width:32px; height:32px; }
}

/* =========================================================
   ✅ FLOATING SOCIAL BAR + MOBILE LANG SWITCH (same container)
   ========================================================= */
#dvFloatSocial.dv-float-social{
  position: fixed;
  left: 14px;
  top: 25%;
  transform: translateY(-50%);
  z-index: 999999;

  display: flex;
  flex-direction: column;
  gap: 8px;

  padding: 8px;
  border-radius: 14px;

  background: rgba(255,255,255,.08);
  border: 1px solid rgba(255,255,255,.16);
  backdrop-filter: blur(14px) saturate(1.2);
  -webkit-backdrop-filter: blur(14px) saturate(1.2);

  box-shadow: 0 10px 32px rgba(0,0,0,.25);

  transition:
    transform .22s ease,
    opacity .22s ease,
    width .35s cubic-bezier(.22,.8,.22,1),
    padding .35s cubic-bezier(.22,.8,.22,1),
    background .35s ease,
    box-shadow .35s ease;
  will-change: transform, opacity;
}

/* desktop toggle */
#dvFloatSocial .dv-float-toggle{
  width: 36px;
  height: 36px;
  border-radius: 999px;
  border: 1px solid rgba(255,255,255,.18);
  background: rgba(0,0,0,.28);
  color: rgba(255,255,255,.9);
  font-size: 16px;
  cursor: pointer;
  transition: background .25s ease, transform .25s ease;
}
#dvFloatSocial .dv-float-toggle:hover{ transform: translateX(1px); }

#dvFloatSocial a{
  width: 36px;
  height: 36px;
  border-radius: 999px;
  display: grid;
  place-items: center;

  background: rgba(255,255,255,.05);
  border: 1px solid rgba(255,255,255,.12);

  transition: transform .25s cubic-bezier(.22,.8,.22,1), opacity .25s ease, background .25s ease;
}
#dvFloatSocial a:hover{
  transform: translateX(2px);
  background: rgba(139,92,246,.22);
}
#dvFloatSocial img{
  width: 16px;
  height: 16px;
  object-fit: contain;
  filter: brightness(1.15);
}

/* collapse state (desktop) */
#dvFloatSocial.is-collapsed{
  padding: 6px;
  background: transparent;
  border-color: transparent;
  box-shadow: none;
  backdrop-filter: none;
  -webkit-backdrop-filter: none;
}
#dvFloatSocial.is-collapsed a{
  opacity: 0;
  transform: translateX(-10px);
  pointer-events: none;
  height: 0;
  margin: 0;
  border: 0;
  padding: 0;
}

/* scroll hide */
#dvFloatSocial.dv-float-social.is-scroll-hidden{
  opacity: 0;
  transform: translateY(-50%) translateX(-12px);
  pointer-events: none;
}

/* ---- mobile language control (inside same container) ---- */
#dvFloatSocial .dv-lang{
  display:none; /* default off (desktop) */
}
#dvFloatSocial .dv-lang-btn{
  width: 38px;
  height: 38px;
  border-radius: 999px;
  border: 1px solid rgba(255,255,255,.16);
  background: rgba(255,255,255,.06);
  color: rgba(255,255,255,.92);
  cursor:pointer;
  display:grid;
  place-items:center;
  font-size: 16px;
}

#dvFloatSocial .dv-lang-panel{
  position:absolute;
  right: 12px;
  bottom: calc(100% + 10px);
  display:none;
  padding: 10px;
  border-radius: 14px;
  background: rgba(10,12,20,.72);
  border: 1px solid rgba(255,255,255,.14);
  backdrop-filter: blur(12px) saturate(1.2);
  -webkit-backdrop-filter: blur(12px) saturate(1.2);
  box-shadow: 0 14px 40px rgba(0,0,0,.45);
  gap: 8px;
  white-space: nowrap;
}
#dvFloatSocial .dv-lang-panel.is-open{ display:flex; }

#dvFloatSocial .dv-lang-panel a{
  width:auto;
  height:auto;
  padding: 8px 10px;
  border-radius: 999px;
  text-decoration:none;
  font-weight: 900;
  font-size: 12px;
  letter-spacing: .08em;
  text-transform: uppercase;

  background: rgba(255,255,255,.06);
  border: 1px solid rgba(255,255,255,.12);
  color: rgba(255,255,255,.88);
}
#dvFloatSocial .dv-lang-panel a.is-active{
  background: rgba(139,92,246,.22);
  border-color: rgba(139,92,246,.35);
  color:#fff;
}

/* Desktop: toggle optional hide (you had that) */
@media (min-width: 769px){
  #dvFloatToggle{ display: none !important; }
}

/* ✅ Mobile bottom pill variant + show language control */
@media (max-width: 768px), (hover: none) {

  #dvFloatSocial.dv-float-social{
    display:flex !important;

    position: fixed !important;
    left: 50% !important;
    bottom: calc(14px + env(safe-area-inset-bottom)) !important;
    top: auto !important;

    transform: translateX(-50%) !important;

    flex-direction: row !important;
    align-items: center !important;
    justify-content: center !important;

    gap: 10px !important;

    padding: 10px 14px !important;
    border-radius: 999px !important;

    background: rgba(10,12,20,.72) !important;
    border: 1px solid rgba(255,255,255,.16) !important;
    box-shadow: 0 12px 30px rgba(0,0,0,.40) !important;

    backdrop-filter: blur(12px) saturate(1.2) !important;
    -webkit-backdrop-filter: blur(12px) saturate(1.2) !important;

    z-index: 999999 !important;

    /* IMPORTANT: never wrap to next line */
    flex-wrap: nowrap !important;
    white-space: nowrap !important;

    transition: transform .22s ease, opacity .22s ease !important;
  }

  /* toggle not useful on mobile bottom bar */
  #dvFloatToggle{ display:none !important; }

  /* icons */
  #dvFloatSocial.dv-float-social a{
    width: 38px !important;
    height: 38px !important;
    display: grid !important;
    place-items: center !important;
    flex: 0 0 auto !important;
  }
  #dvFloatSocial.dv-float-social img{
    width: 18px !important;
    height: 18px !important;
  }

  /* show mobile language block inside the same bar (right side) */
  #dvFloatSocial .dv-lang{
    display:flex !important;
    align-items:center !important;
    gap: 8px !important;
    flex: 0 0 auto !important;
    margin-left: 6px !important;
    position: relative !important;
  }

  /* dropdown position relative to bar */
  #dvFloatSocial .dv-lang-panel{
    right: 0 !important;
    bottom: calc(100% + 10px) !important;
  }

  /* ✅ FIX: on mobile, is-scroll-hidden must also hide opacity/pointer-events */
  #dvFloatSocial.dv-float-social.is-scroll-hidden{
    opacity: 0 !important;
    visibility: hidden !important;
    pointer-events: none !important;
    transform: translateX(-50%) translateY(14px) !important;
  }
}

/* extra-small: make icons slightly smaller if needed */
@media (max-width: 360px){
  #dvFloatSocial.dv-float-social a{ width:34px !important; height:34px !important; }
  #dvFloatSocial.dv-float-social img{ width:16px !important; height:16px !important; }
  #dvFloatSocial .dv-lang-btn{ width:34px !important; height:34px !important; }
}

/* ===== Visual separator between social icons and language ===== */
#dvFloatSocial .dv-lang{
  position: relative;
  margin-left: 10px;
  padding-left: 12px;
}

#dvFloatSocial .dv-lang::before{
  content:"";
  position:absolute;
  left:0;
  top: 6px;
  bottom: 6px;
  width:1px;
  background: linear-gradient(
    180deg,
    transparent,
    rgba(255,255,255,.35),
    transparent
  );
  opacity:.7;
}

`;

    document.head.appendChild(style);
  }

  const THEME_KEY  = "dvayd_theme";
  const DIM_VALUE  = "dim";
  const THEME_ATTR = "data-theme"; // <html data-theme="dim">

  function getLang() {
    const m = location.pathname.match(/^\/(de|en|tr|fr)(\/|$)/);
    return m ? m[1] : "de";
  }

  function getPageKey(path, lang) {
    const r = ROUTES[lang];
    for (const [k, v] of Object.entries(r)) {
      if (path === v || path.startsWith(v)) return k;
    }
    return "home";
  }

  // Theme helpers
  function getStoredTheme(){
    try { return localStorage.getItem(THEME_KEY) || ""; } catch { return ""; }
  }
  function setStoredTheme(v){
    try { localStorage.setItem(THEME_KEY, v); } catch {}
  }
  function applyTheme(v){
    const root = document.documentElement;
    if (v === DIM_VALUE) root.setAttribute(THEME_ATTR, DIM_VALUE);
    else root.removeAttribute(THEME_ATTR);
  }
  function isDimActive(){
    return document.documentElement.getAttribute(THEME_ATTR) === DIM_VALUE;
  }

  function socialHTML() {
    // NOTE: language UI is inside the same container, but only shown on mobile by CSS
    return `
      <div class="dv-float-social" id="dvFloatSocial" aria-label="Social Bar">
        <button
          type="button"
          class="dv-float-toggle"
          id="dvFloatToggle"
          aria-label="Social Bar umschalten"
          aria-expanded="true">‹</button>

        <a href="${SOCIAL.x.href}" target="_blank" rel="noopener" aria-label="${SOCIAL.x.label}">
          <img src="${SOCIAL.x.icon}" alt="${SOCIAL.x.label}">
        </a>
        <a href="${SOCIAL.instagram.href}" target="_blank" rel="noopener" aria-label="${SOCIAL.instagram.label}">
          <img src="${SOCIAL.instagram.icon}" alt="${SOCIAL.instagram.label}">
        </a>
        <a href="${SOCIAL.youtube.href}" target="_blank" rel="noopener" aria-label="${SOCIAL.youtube.label}">
          <img src="${SOCIAL.youtube.icon}" alt="${SOCIAL.youtube.label}">
        </a>
        <a href="${SOCIAL.linkedin.href}" target="_blank" rel="noopener" aria-label="${SOCIAL.linkedin.label}">
          <img src="${SOCIAL.linkedin.icon}" alt="${SOCIAL.linkedin.label}">
        </a>

        <!-- ✅ MOBILE LANG SWITCH (same container, right side) -->
        <div class="dv-lang" id="dvFloatLang" aria-label="Language switch (mobile)">
          <button class="dv-lang-btn" id="dvLangBtn" type="button" aria-label="Sprache wählen" aria-expanded="false">
            <img src="/assets/icons/language.png";" alt="Language" class="dv-lang-ico">
          </button>
          <div class="dv-lang-panel" id="dvLangPanel" role="menu" aria-label="Sprachen">
            <a data-lang-float="de" role="menuitem">DE</a>
            <a data-lang-float="en" role="menuitem">EN</a>
            <a data-lang-float="tr" role="menuitem">TR</a>
            <a data-lang-float="fr" role="menuitem">FR</a>
          </div>
        </div>
      </div>
    `;
  }

  function headerHTML(lang) {
    const L = LABELS[lang] || LABELS.de;

    return `
      <div class="hdr">
        <div class="hdr-inner">
          <a class="brand" href="${ROUTES[lang].home}" aria-label="Homepage">
            <img src="${LOGO_SRC}" alt="DVAYD Publishing Logo" />
            <span>DVAYD Publishing</span>
          </a>

          <div class="right">
            <div class="hdr-search">
              <form class="site-search" role="search" autocomplete="off">
                <input
                  id="site-search-input"
                  type="search"
                  placeholder="${L.search_ph}"
                  aria-label="${L.search}"
                />
                <button type="submit" class="search-icon" aria-label="${L.search}">
                  <img src="/assets/icons/lupe.png" alt="" />
                </button>
                <div class="search-dd" id="site-search-dd"></div>
              </form>
            </div>

            <button class="theme-btn" id="themeToggle" type="button" aria-label="Toggle dim mode" title="${L.theme}">
              <span class="moon" aria-hidden="true">🌙</span>
              <span class="sun" aria-hidden="true">☀️</span>
            </button>

            <div class="langs" aria-label="Language switch">
              <a data-lang="de">DE</a><span class="sep">|</span>
              <a data-lang="en">EN</a><span class="sep">|</span>
              <a data-lang="tr">TR</a><span class="sep">|</span>
              <a data-lang="fr">FR</a>
            </div>

            <button class="burger" type="button" aria-label="Menu" aria-expanded="false">
              <span class="icon" aria-hidden="true"><i></i><i></i><i></i></span>
            </button>
          </div>
        </div>
      </div>

      <div class="overlay" data-overlay></div>

      <aside class="drawer" data-drawer aria-label="Menu">
        <div class="drawer-top">
          <div class="title">${L.menu}</div>
          <button class="close" type="button" data-close aria-label="Close">✕</button>
        </div>
        <nav>
          <!-- ✅ NEW: Startseite/Home link -->
          <a href="${ROUTES[lang].home}">${L.home}</a>

          <a href="${ROUTES[lang].about}">${L.about}</a>
          <a href="${ROUTES[lang].projects}">${L.projects}</a>
          <a href="${ROUTES[lang].services}">${L.services}</a>
          <a href="${ROUTES[lang].process}">${L.process}</a>
          <a href="${ROUTES[lang].blog}">${L.blog}</a>
          <a href="${ROUTES[lang].contact}">${L.contact}</a>
        </nav>
      </aside>
    `;
  }

  function debounce(fn, wait = 180) {
    let t;
    return (...args) => {
      clearTimeout(t);
      t = setTimeout(() => fn(...args), wait);
    };
  }

  function ensureSocialBarExists() {
    if (document.getElementById("dvFloatSocial")) return;
    const wrapper = document.createElement("div");
    wrapper.innerHTML = socialHTML();
    document.body.appendChild(wrapper.firstElementChild);
  }

  function initSocialBarLogic() {
    const bar = document.getElementById("dvFloatSocial");
    const btn = document.getElementById("dvFloatToggle");

    const langBtn = document.getElementById("dvLangBtn");
    const langPanel = document.getElementById("dvLangPanel");

    if (!bar) return;

    // Restore collapsed state (desktop mainly)
    function setState(collapsed){
      bar.classList.toggle("is-collapsed", collapsed);
      if (btn){
        btn.textContent = collapsed ? "›" : "‹";
        btn.setAttribute("aria-expanded", collapsed ? "false" : "true");
      }
      try { localStorage.setItem(SOCIAL_STATE_KEY, collapsed ? "1" : "0"); } catch {}
    }

    const storedCollapsed = (() => {
      try { return localStorage.getItem(SOCIAL_STATE_KEY) === "1"; } catch { return false; }
    })();
    setState(storedCollapsed);

    btn?.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      setState(!bar.classList.contains("is-collapsed"));
    });

    // Language dropdown
    function openLang(){
      if (!langPanel || !langBtn) return;
      langPanel.classList.add("is-open");
      langBtn.setAttribute("aria-expanded","true");
    }
    function closeLang(){
      if (!langPanel || !langBtn) return;
      langPanel.classList.remove("is-open");
      langBtn.setAttribute("aria-expanded","false");
    }
    function toggleLang(){
      if (!langPanel) return;
      langPanel.classList.contains("is-open") ? closeLang() : openLang();
    }

    langBtn?.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      toggleLang();
    });

    // Hide on scroll down, show on scroll up (works on desktop + mobile)
    let lastY = window.scrollY || 0;
    let ticking = false;

    function hideBar(){ bar.classList.add("is-scroll-hidden"); closeLang(); }
    function showBar(){ bar.classList.remove("is-scroll-hidden"); }

    function onScroll(){
      const y = window.scrollY || 0;
      const delta = y - lastY;
      lastY = y;

      if (Math.abs(delta) < 3) return;
      if (delta > 0) hideBar();
      else showBar();
    }

    window.addEventListener("scroll", () => {
      if (ticking) return;
      ticking = true;
      requestAnimationFrame(() => {
        onScroll();
        ticking = false;
      });
    }, { passive:true });

    document.addEventListener("click", (e) => {
      // close language if click outside the bar
      if (!bar.contains(e.target)) closeLang();
    });
    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape") closeLang();
    });

    // initial visible
    showBar();
  }

  function syncFloatingLangLinks(lang, pageKey){
    const panel = document.getElementById("dvLangPanel");
    if (!panel) return;

    panel.querySelectorAll("[data-lang-float]").forEach(a => {
      const targetLang = a.getAttribute("data-lang-float");
      const href = (ROUTES[targetLang] && ROUTES[targetLang][pageKey]) || ROUTES[targetLang]?.home || "/";

      a.setAttribute("href", href);
      a.classList.toggle("is-active", targetLang === lang);

      a.addEventListener("click", () => {
        // close after selection (nice on mobile)
        const langBtn = document.getElementById("dvLangBtn");
        panel.classList.remove("is-open");
        langBtn?.setAttribute("aria-expanded","false");
      }, { once:false });
    });
  }

  function init() {
    injectHeaderCSS();

    const mount = document.getElementById("site-header");
    if (!mount) return;

    // ensure social bar exists on every page
    ensureSocialBarExists();
    initSocialBarLogic();

    // apply stored theme ASAP
    const storedTheme = getStoredTheme();
    applyTheme(storedTheme);

    const lang = getLang();
    const path = location.pathname;
    const pageKey = getPageKey(path, lang);

    // IMPORTANT: sync floating language links once we know pageKey/lang
    syncFloatingLangLinks(lang, pageKey);

    mount.innerHTML = headerHTML(lang);

    const hdr = mount.querySelector(".hdr");
    const overlay = mount.querySelector("[data-overlay]");
    const drawer = mount.querySelector("[data-drawer]");
    const burger = mount.querySelector(".burger");
    const closeBtn = mount.querySelector("[data-close]");

    // ===== Sync CSS var --hdr-h to real header height =====
    function syncHeaderHeight(){
      if (!hdr) return;
      const h = Math.round(hdr.getBoundingClientRect().height);
      document.documentElement.style.setProperty("--hdr-h", `${h}px`);
    }
    syncHeaderHeight();
    window.addEventListener("resize", syncHeaderHeight);
    if ("ResizeObserver" in window) {
      const ro = new ResizeObserver(() => syncHeaderHeight());
      ro.observe(hdr);
    }

    // ===== Theme toggle =====
    const themeBtn = mount.querySelector("#themeToggle");
    const syncThemeBtn = () => {
      if (!themeBtn) return;
      themeBtn.classList.toggle("is-dim", isDimActive());
      themeBtn.setAttribute("aria-pressed", isDimActive() ? "true" : "false");
    };
    syncThemeBtn();

    themeBtn?.addEventListener("click", () => {
      const next = isDimActive() ? "" : DIM_VALUE;
      applyTheme(next);
      setStoredTheme(next);
      syncThemeBtn();
    });

    // ===== Drawer open/close =====
    const openMenu = () => {
      burger?.setAttribute("aria-expanded", "true");
      overlay?.classList.add("is-open");
      drawer?.classList.add("is-open");
      document.documentElement.style.overflow = "hidden";
      hdr?.classList.remove("is-hidden");
    };
    const closeMenu = () => {
      burger?.setAttribute("aria-expanded", "false");
      overlay?.classList.remove("is-open");
      drawer?.classList.remove("is-open");
      document.documentElement.style.overflow = "";
    };

    burger?.addEventListener("click", () => {
      const isOpen = burger.getAttribute("aria-expanded") === "true";
      isOpen ? closeMenu() : openMenu();
    });
    overlay?.addEventListener("click", closeMenu);
    closeBtn?.addEventListener("click", closeMenu);
    document.addEventListener("keydown", (e) => { if (e.key === "Escape") closeMenu(); });

    // ===== Active language link (header desktop) =====
    mount.querySelectorAll("[data-lang]").forEach(a => {
      const targetLang = a.dataset.lang;
      a.href = (ROUTES[targetLang] && ROUTES[targetLang][pageKey]) || ROUTES[targetLang].home;
      a.classList.toggle("is-active", targetLang === lang);
    });

    // ===== Header hide/show on scroll =====
    let lastY = window.scrollY || 0;
    let ticking = false;
    const SCROLL_ON_AT = 8, HIDE_AFTER = 120, DELTA = 6;

    function onScroll() {
      const y = window.scrollY || 0;
      const menuOpen = burger?.getAttribute("aria-expanded") === "true";
      hdr?.classList.toggle("is-scrolled", y > SCROLL_ON_AT);
      if (menuOpen) { lastY = y; return; }

      const diff = y - lastY;
      if (Math.abs(diff) < DELTA) return;

      if (diff > 0 && y > HIDE_AFTER) hdr?.classList.add("is-hidden");
      else hdr?.classList.remove("is-hidden");

      lastY = y;
    }

    window.addEventListener("scroll", () => {
      if (!ticking) {
        window.requestAnimationFrame(() => { onScroll(); ticking = false; });
        ticking = true;
      }
    }, { passive: true });
    onScroll();

    // ===== Pagefind dropdown search =====
    const form = mount.querySelector(".site-search");
    const input = mount.querySelector("#site-search-input");
    const dd = mount.querySelector("#site-search-dd");
    if (!form || !input || !dd) return;

    let pagefindMod = null;
    let pagefindLoading = false;

    async function ensurePagefind() {
      if (pagefindMod) return pagefindMod;
      if (pagefindLoading) return null;
      pagefindLoading = true;

      try {
        let mod = await import(PAGEFIND_MODULE_PATH);
        pagefindMod = mod?.default ? mod.default : mod;
        return pagefindMod;
      } catch (e) {
        console.error("Pagefind failed to load:", e);
        dd.classList.add("is-open");
        dd.innerHTML = `<div class="dd-empty">Pagefind konnte nicht geladen werden.</div>`;
        return null;
      } finally {
        pagefindLoading = false;
      }
    }

    function openDD(){ dd.classList.add("is-open"); }
    function closeDD(){ dd.classList.remove("is-open"); dd.innerHTML = ""; }

    function escapeHTML(s) {
      return String(s || "")
        .replaceAll("&","&amp;")
        .replaceAll("<","&lt;")
        .replaceAll(">","&gt;")
        .replaceAll('"',"&quot;")
        .replaceAll("'","&#039;");
    }

    async function runSearch(q) {
      q = (q || "").trim();
      if (!q) { closeDD(); return; }

      openDD();
      dd.innerHTML = `<div class="dd-loading">Suche…</div>`;

      const pf = await ensurePagefind();
      if (!pf || typeof pf.search !== "function") {
        dd.innerHTML = `<div class="dd-empty">Pagefind konnte nicht geladen werden.</div>`;
        return;
      }

      try {
        const res = await pf.search(q);
        const results = res?.results || [];

        if (!results.length) {
          dd.innerHTML = `<div class="dd-empty">Keine Ergebnisse für „${escapeHTML(q)}“</div>`;
          return;
        }

        const top = results.slice(0, 6);
        const data = await Promise.all(top.map(r => r.data()));

        dd.innerHTML = data.map(d => {
          const url = d.url || "#";
          const title = escapeHTML(d.meta?.title || d.title || url);
          const excerpt = (d.excerpt || "").trim(); // can contain <mark>
          const niceUrl = escapeHTML(url);

          return `
            <a class="dd-row" href="${url}">
              <div class="dd-title">${title}</div>
              <div class="dd-meta">${excerpt ? excerpt : niceUrl}</div>
            </a>
          `;
        }).join("");

      } catch (e) {
        console.error("Pagefind search error:", e);
        dd.innerHTML = `<div class="dd-empty">Fehler bei der Suche.</div>`;
      }
    }

    const runSearchDebounced = debounce(runSearch, 220);

    form.addEventListener("submit", (e) => {
      e.preventDefault();
      runSearch(input.value);
    });

    input.addEventListener("focus", () => {
      ensurePagefind();
      if (dd.innerHTML.trim()) openDD();
    });

    input.addEventListener("input", () => {
      runSearchDebounced(input.value);
    });

    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape") closeDD();
    });

    document.addEventListener("click", (e) => {
      if (!form.contains(e.target)) closeDD();
    });
  }

  document.addEventListener("DOMContentLoaded", init);
})();
